- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Get Config for VyOS devices
      vyos.vyos.vyos_facts:
        gather_subnet: all
    - name: Display the config
      debug:
        msg: "The host name is {{ ansible_net_hostname}} and the OS is {{ ansible_net_version }}"