#- hosts: localhost
#  tasks:
#    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }} c={{ item[2] }}"
#      with_nested:
#        - [ 'red', 'blue', 'green' ]
#        - [ 1, 2, 3 ]
#        - [ 'up', 'down', 'strange']

# you can reference a raw variable name without putting it in {{ brackets }}

- hosts: localhost
  vars:
    listvar1:
    - 'a'
    - 'b'
    - 'c'
  tasks:

  - name: configure users
    user: name={{ item }} state=present
#    shell: echo "adding {{ item }} as a user"
    with_items:
      - testuser1
      - testuser2

  - name: remove users
    user: name={{ item }} state=absent
#    shell: echo "removingg {{ item }} as a user"
    with_items:
      - testuser1
      - testuser2