#- hosts: localhost
#  tasks:
#    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }} c={{ item[2] }}"
#      with_nested:
#        - [ 'red', 'blue', 'green' ]
#        - [ 1, 2, 3 ]
#        - [ 'up', 'down', 'strange']

# you can reference a raw variable name without putting it in {{ brackets }}

- hosts: localhost
  gather_facts: no
  vars:
    users:
      - 'testuser1'
      - 'testuser2'
  tasks:

  - name: configure users
    user: name={{ item }} state=present
#   shell: echo "adding {{ item }} as a user"
    loop: "{{ users }}"

  - name: remove users
    user: name={{ item }} state=absent
#    shell: echo "removingg {{ item }} as a user"
    loop: "{{ users }}"

  - name: delete home dir for removed users
    ansible.builtin.file:
      state: absent
      path: "/home/{{ item }}"
    loop: "{{ users }}"

  - name: debugging
    ansible.builtin.debug:
      msg: "Finished deleting {{ item }}"
    loop: "{{ users }}"
